export const componentRegistry = Object.freeze([
  { id: 'ui.button', name: 'Button', category: 'control', module: './button.js', consumers: ['tasks', 'search', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'ui.tag', name: 'Tag', category: 'display', module: './tag.js', consumers: ['tasks'], dsBinding: null },
  { id: 'data.table', name: 'Table', category: 'data-display', module: './table.js', consumers: ['search', 'documents', 's-center-prototype'], dsBinding: null },
  { id: 'data.task-list-card', name: 'Task List Card', category: 'data-display', module: './task-list-card.js', consumers: ['tasks'], dsBinding: null },
  { id: 'data.card', name: 'Card', category: 'data-display', module: './card.js', consumers: ['s-center-prototype'], dsBinding: null },
  { id: 'data.parameter-pair', name: 'Parameter Pair', category: 'data-display', module: './parameter-pair.js', consumers: ['s-center-prototype'], dsBinding: null },
  { id: 'data.progress-ring', name: 'Progress Ring', category: 'data-display', module: './progress-ring.js', consumers: ['s-center-prototype'], dsBinding: null },
  { id: 'data.chessboard', name: 'Chessboard', category: 'data-display', module: './chessboard.js', consumers: ['s-center-prototype'], dsBinding: null },
  { id: 'data.file-item', name: 'File Item', category: 'data-display', module: './file-item.js', consumers: ['documents'], dsBinding: null },
  { id: 'data.file-list', name: 'File List', category: 'data-display', module: './file-list.js', consumers: ['documents'], dsBinding: null },
  { id: 'control.document-editor-toolbar', name: 'Document Editor Toolbar', category: 'control', module: './document-editor-toolbar.js', consumers: ['documents'], dsBinding: null },
  { id: 'data.document-preview-surface', name: 'Document Preview Surface', category: 'data-display', module: './document-preview-surface.js', consumers: ['documents'], dsBinding: null },
  { id: 'navigation.document-preview', name: 'Document Preview Navigation', category: 'navigation', module: './document-preview-navigation.js', consumers: ['documents'], dsBinding: null },
  { id: 'ui.input', name: 'Input', category: 'control', module: './input.js', consumers: ['tasks', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'ui.textarea', name: 'Textarea', category: 'control', module: './textarea.js', consumers: ['documents'], dsBinding: null },
  { id: 'ui.select', name: 'Select', category: 'control', module: './select.js', consumers: ['tasks', 'documents', 's-center-prototype'], dsBinding: null },
  { id: 'ui.multi-select', name: 'MultiSelect', category: 'control', module: './multi-select.js', consumers: ['tasks', 'search'], dsBinding: null },
  { id: 'ui.checkbox', name: 'Checkbox', category: 'control', module: './checkbox.js', consumers: ['tasks', 'search', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'ui.chip', name: 'Chip', category: 'control', module: './chip.js', consumers: ['tasks'], dsBinding: null },
  { id: 'ui.switch', name: 'Switch', category: 'control', module: './switch.js', consumers: ['tasks', 'search', 'documents'], dsBinding: null },
  { id: 'ui.segmented-control', name: 'Segmented Control', category: 'control', module: './segmented-control.js', consumers: ['tasks', 'documents', 'document-templates'], dsBinding: null },
  { id: 'ui.tabs', name: 'Tabs', category: 'navigation', module: './tabs.js', consumers: ['search', 's-center-prototype'], dsBinding: null },
  { id: 'navigation.breadcrumbs', name: 'Breadcrumbs', category: 'navigation', module: './breadcrumbs.js', consumers: ['tasks', 'documents', 'search'], dsBinding: null },
  { id: 'navigation.tree', name: 'Tree', category: 'navigation', module: './tree.js', consumers: ['search', 's-center-prototype'], dsBinding: null },
  { id: 'ui.tree-select', name: 'TreeSelect', category: 'control', module: './tree-select.js', consumers: ['search'], dsBinding: null },
  { id: 'pattern.accordion', name: 'Accordion', category: 'disclosure', module: './accordion.js', consumers: ['tasks', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'pattern.pagination', name: 'Pagination', category: 'navigation', module: './pagination.js', consumers: ['tasks', 'search', 'documents'], dsBinding: null },
  { id: 'pattern.menu', name: 'Menu', category: 'overlay', module: './menu.js', consumers: ['search', 's-center-prototype'], dsBinding: null },
  { id: 'pattern.tooltip', name: 'Tooltip', category: 'overlay', module: './tooltip.js', consumers: ['s-center-prototype'], dsBinding: null },
  { id: 'pattern.resize-handle', name: 'Resize Handle', category: 'utility', module: './resize-handle.js', consumers: ['tasks', 'documents', 'document-templates', 'search', 's-center-prototype'], dsBinding: null },
  { id: 'utility.icon', name: 'Icon', category: 'utility', module: './icon.js', consumers: ['search', 's-center-prototype'], dsBinding: null },
  { id: 'utility.package-disclosure-icon', name: 'Package Disclosure Icon', category: 'utility', module: './package-disclosure-icon.js', consumers: ['search', 'documents', 's-center-prototype'], dsBinding: null },
  { id: 'pattern.drawer', name: 'Drawer', category: 'overlay', module: './drawer.js', consumers: ['tasks', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'pattern.modal', name: 'Modal', category: 'overlay', module: './modal.js', consumers: ['tasks', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'pattern.bulk-action-bar', name: 'Bulk Action Bar', category: 'overlay', module: './bulk-action-bar.js', consumers: [], dsBinding: null },
  { id: 'feedback.alert', name: 'Alert', category: 'feedback', module: './alert.js', consumers: ['tasks', 'search', 'documents', 'document-templates', 's-center-prototype'], dsBinding: null },
  { id: 'feedback.toast', name: 'Toast', category: 'feedback', module: './toast.js', consumers: ['tasks', 'search', 'documents', 'document-templates'], dsBinding: null },
  { id: 'feedback.empty-state', name: 'Empty State', category: 'feedback', module: './empty-state.js', consumers: ['search', 's-center-prototype'], dsBinding: null },
  { id: 'feedback.empty-state-illustration', name: 'Empty State Illustration', category: 'feedback', module: './empty-state-illustration.js', consumers: ['search'], dsBinding: null },
]);

export function getComponentDefinition(id) {
  return componentRegistry.find(component => component.id === id) || null;
}
